UserStateProcessor
k1cker666/Project2.TGBot pull request #11
Opened 2024-04-11 15:45 UTC by k1cker666

2024-04-12 14:30 UTC, VIkDema requested changes

2024-04-12 14:30 UTC, VIkDema commented on bot/src/db/redis.py
> +    connection = redis.StrictRedis(
А почему StrictRedis теперь?

2024-04-12 14:30 UTC, VIkDema commented on bot/src/db/redis.py
> +def create_connectrion(config: RedisDB, decode_responses=True, charset="utf-8"):
А зачем charset передавать в create_connection?
кстати опечатка "connectrion"

2024-04-12 14:30 UTC, VIkDema commented on bot/src/db/redis.py
> +        logger.error('Application was not started')
Application was not started - это не error message, а info

2024-04-12 14:30 UTC, VIkDema commented on bot/src/dependencies.py
> +    bot_token: str
bot_token это данные, не нужно хранить их в Dependecies
Если потом добавим что-то еще, будет соблазн ну понимаешь)
Храни лучше класс Config

2024-04-12 14:30 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +        ttl = timedelta(minutes=10)
Вот ttl можно в конфиг положить)

2024-04-12 14:30 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +    def set_data(self, user_id: str, data: str):
data то не str)
по сути нам нужен будет dict

2024-04-12 14:30 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +    def __init__(self, connecton: redis.Redis):
connecton, conn и connection
какие еще варианты?)

2024-04-12 14:30 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +        return self.conn.hgetall(user_id)
Тут не data вернется ведь?

2024-04-12 14:30 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +from datetime import timedelta
Нет тестов на UserStateProcessor

2024-04-12 14:43 UTC, k1cker666 commented on bot/src/db/redis.py
> +    connection = redis.StrictRedis(
забыл поменять обратно, в более ранней версии redis-py StrictRedis лучше работал с типами. ща уже это то же самое

2024-04-12 14:59 UTC, k1cker666 commented on bot/src/components/user_state_processor.py
> +        ttl = timedelta(minutes=10)
а что именно мне в конфиг положить? количество минут?

2024-04-12 15:06 UTC, k1cker666 commented on bot/src/components/user_state_processor.py
> +    def set_data(self, user_id: str, data: str):
то есть мне надо вносить data.key и data.value?

2024-04-12 15:09 UTC, k1cker666 commented on bot/src/components/user_state_processor.py
> +        return self.conn.hgetall(user_id)
тут вернется весь хэш под user_id

2024-04-13 18:02 UTC, VIkDema requested changes

2024-04-14 11:37 UTC, VIkDema commented on bot/tests/conftest.py
> +def redis_connect():
def redis_connect(config_init):
Разве так не работает?

2024-04-14 11:37 UTC, merged