Lesson component
k1cker666/Project2.TGBot pull request #12
Opened 2024-04-14 11:40 UTC by k1cker666

2024-04-14 11:43 UTC, VIkDema commented on bot/src/bot.py
> +    application.add_handler(MessageHandler(filters.Text("Начать урок"), start_lesson_with_deps))
А это не надо ведь теперь?

2024-04-14 11:43 UTC, VIkDema commented on bot/src/bot.py
> +async def start_lesson(
И это не надо получается

2024-04-23 06:56 UTC, k1cker666 commented
LessonInit возвращает константу
Callback typeddict объеденен
В lesson_handler прокидывается user_state_proc
Введен ttl для теста
Кнопки с словами выводятся в чат

2024-04-24 06:28 UTC, VIkDema commented on bot/main.py
>  def main():
ой не нравится мне как выглядит main.py
https://tracker.yandex.ru/TGBOT-20 - тут подумаю, поправим потом

2024-04-24 06:28 UTC, VIkDema commented on bot/src/bot.py
> +    def freeze_deps(func):
freeze? 
почему не parital

2024-04-24 06:28 UTC, VIkDema commented on bot/src/bot.py
> +    await query.answer()
Это зачем вызывается?

2024-04-24 06:28 UTC, VIkDema commented on bot/src/bot.py
> +        return BaseCallback(*data)
Вот как будто сейчас Callback избыточен
нужно написать более просто класс 
callbackData

С двумя методами from_string и to_string

2024-04-24 06:28 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +    def set_state(self, user_id: str, state: State, ttl: int = None):
Не очень нравится передача ttl в методы
Лучше в конструкторе тогда уж

2024-04-24 14:29 UTC, k1cker666 commented on bot/src/bot.py
> +    await query.answer()
забыл убрать это, проверял что это делает) вроде как с помощью этого метода оповестить пользователя что нажатие на кнопку обрабатывается

2024-04-24 14:33 UTC, k1cker666 commented on bot/src/bot.py
> +    def freeze_deps(func):
слово из описания функции взял. переименовать partial_deps?

2024-04-24 14:36 UTC, k1cker666 commented on bot/src/components/user_state_processor.py
> +    def set_state(self, user_id: str, state: State, ttl: int = None):
добавил это чтобы в обычной работе был большой ttl, а в тестах короткий, в коде не надо передавать ttl, ток в тестах

2024-04-24 16:50 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +    def set_state(self, user_id: str, state: State, ttl: int = None):
писать код целевой ради тестов это плохо

2024-04-24 16:50 UTC, VIkDema commented on bot/src/components/user_state_processor.py
> +    def set_state(self, user_id: str, state: State, ttl: int = None):
Откуда другие будут знать, что это только для тестов

2024-04-24 16:51 UTC, VIkDema commented on bot/src/bot.py
> +    def freeze_deps(func):
partial_deps нравится больше

2024-04-24 18:02 UTC, VIkDema requested changes

2024-04-24 18:02 UTC, VIkDema commented on bot/src/components/lesson_handler.py
> +    async def handle_callback(
Исправить размер функции

2024-04-26 16:55 UTC, merged