Wordinprogress repository
k1cker666/Project2.TGBot pull request #13
Opened 2024-04-25 18:25 UTC by k1cker666

2024-04-25 19:52 UTC, k1cker666 commented
последние 3 коммита:
только 1 парсинг для callback_data и она прокидывается далее
CallbackData в исходном виде, не скипает None
убраны f string где они не нужны

2024-04-30 19:05 UTC, VIkDema commented
название pr-та

2024-04-30 19:36 UTC, VIkDema commented
тесты на методы репозиториев

2024-04-30 19:37 UTC, VIkDema commented
и не забыть в миграцию добавить фичу на extension

2024-05-01 11:24 UTC, VIkDema requested changes

2024-05-02 06:00 UTC, VIkDema commented on bot/migrations/01_add_tables.sql
> +create unique index if not exists user_tg_login on users (tg_login);
unique index точно unique? вроде хотели чтобы у одного tg_login могло быть несколько акков

2024-05-02 06:01 UTC, merged