Word repository
k1cker666/Project2.TGBot pull request #8
Opened 2024-04-06 11:55 UTC by k1cker666

2024-04-06 16:25 UTC, k1cker666 commented
в коммите [schema tgbot changed to db tgbot](https://github.com/k1cker666/Project2.TGBot/pull/8/commits/bfbaaac692fdc58c1aaef8a9d8e0483ba99dd0c3) перешел от создания схемы tgbot к созданию новой базы данных tgbot, соответственно переписал немного run_migrations, и в psql.py идет коннект сразу к бд tgbot.
но есть прикол
чтобы запустить бота идет проверка while ! pg_isready -d tgbot -h postgres -p 5432 -U postgres; do sleep 10; done флаг -d должен проверять коннект именно бд tgbot, но почему то выдает положительный ответ на моменте когда сервер запущен, а база не создана, поэтому увеличил время сна до 10 секунд на всякий случай

2024-04-07 06:06 UTC, VIkDema commented on bot/src/db/psql.py
> +            autocommit = True
хитро)

2024-04-07 06:07 UTC, VIkDema commented on bot/src/dependencies.py
> +    psql_connect: Connection
А теперь можно в dependencies не записывать psql_connect)

2024-04-07 06:07 UTC, VIkDema commented on bot/src/models/word.py
> +    word_id: int
А почему не enum используем?

2024-04-07 06:11 UTC, VIkDema requested changes

2024-04-07 06:11 UTC, VIkDema commented on bot/src/repository/word_repository.py
> +class WordRepository:
пустую строчку между 3 и 4

2024-04-07 06:11 UTC, VIkDema commented on bot/src/repository/word_repository.py
> +    def fetch(self, id):
def fetch(self, id):
Давай явно напишем что возвращает
def fetch(self, id) -> Word:

2024-04-07 06:11 UTC, VIkDema commented on bot/tests/test_fetch.py
> +            with conn.cursor() as cur:
Здесь нужно создать WordRespository)
А то непонятно что тестим)

А еще непонятно, откуда эти данные должны появиться в бд)

2024-04-07 09:13 UTC, k1cker666 commented
в этом коммите получилось много маленьких изменений:

deps больше не записывают поле psql_connect
в main.py закрываются соединения к бд(вроде как полезно=))
wordrepo: fetch(self, id) => fetch(self, id, language)
test_fetch засплитил на test_fetch_word/test_fetch_nonetype
word model: level & language теперь enums
в миграциях для таблицы word заменил word_id serial ->  word_id int
чуть дополнил логи

2024-04-07 09:26 UTC, merged